exports = {
    "Show first title":"Заголовок блока",
    "Show second title":"Подзаголовок блока",
    "Grayscale logo":"Обесцветить логотипы",
    "Background color:":"Цвет фона:",
    "Show text under the form":"Текст под формой",
    "Countdown color:":"Цвет таймера:",
    "Second title color:":"Цвет второго заголовка:",
    "Background:":"Фон:",
    "Show list":"Список",
    "Show name cell":"Имя ячейки",
    "Show description cell":"Подзаголовок",
    "Show border from image":"Рамка у изображения",
    "Show policy":"Политика конфиденциальности",
    "Show copyright":"Авторские права",
    "Add placemark":"Добавить маркер",
    "center":"центр",
    "Show text":"Показать текст",
    "Name":"Имя",
    "Address":"Адрес",
    "Color":"Цвет:",
    "Upload file":"Загрузить файл",
    "Video":"Видео",
    "Video url (youtube or vimeo):":"Ссылка на видео (youtube или vimeo)",
    "example: www.youtube.com\/embed\/xbK8rl9wH4Q":"пример: www.youtube.com\/embed\/xbK8rl9wH4Q",
    "Image":"Изображение",
    "Select file":"Выбрать файл",
    "Upload image file":"Загрузить изображение",
    "Order form":"Форма заказа",
    "Button text:":"Текст кнопки:",
    "Button color:":"Цвет кнопки:",
    "Form:":"Форма",
    "Show form":"Показать форму",
    "Show success window":"Показать окно благодарности",
    "Add Item":"Добавить",
    "Media files":"Медиа файлы",
    "Upload image":"Загрузить изображение",
    "Image title:":"Название картинки:",
    "Image description:":"Описание картинки:",
    "Countdown settings":"Настройки таймера",
    "Exact date<br>":"Дата окончания<br>",
    "Every month<br>":"Каждый месяц<br>",
    "Every week<br>":"Каждую неделю<br>",
    "Every day<br>":"Каждый день<br>",
    "Date:":"Дата:",
    "Day:":"День:",
    "Day of week:":"День недели:",
    "Time:":"Время:",
    "Map":"Карта",
    "Logotype":"Логотип",
    "Image logo":"Изображение",
    "Text name logo":"Текст",
    "Company name:":"Название компании:",
    "Font settings:":"Настройки шрифта:",
    "Size:":"Размер:",
    "Field label":"Название поля",
    "Field description":"Описание поля",
    "Is required?":"Обязательное поле",
    "Option 1\\nOption 2\\nOption 3":"Опция 1\\n Опция 2\\n Опция 3\\n",
    "Options":"Опции",
    "Form":"Форма",
    "Add Field":"Добавить поле",
    "Sure to remove component?":"Удалить данный блок?",
    "Settings":"Настройки",
    "Icons":"Иконки",
    "Show description and order button":"Кнопка заявки и описание",
    "Show order button":"Кнопка заявки",
    "Show border from icon":"Рамка у иконки",
    "Show name benefit":"Название преимущества",
    "Show description benefit":"Описание преимущества",
    "Show name step":"Название шага",
    "Show description step":"Описание шага",
    "Show image":"Изображение",
    "Icons color:":"Цвет иконок:",
    "black":"черный",
    "grey":"серый",
    "white":"белый",
    "Digits color:":"Цвет таймера",
    "Show name":"Имя",
    "Show description":"Описание",
    "Show price":"Цена",
    "Show text above order button":"Текст над кнопкой заказа",
    "Show image shadow":"Добавить тень",
    "Image size:":"Размер изображения:",
    "middle<br>":"средний<br>",
    "large":"большой",
    "Image shape:":"Форма изображения:",
    "circle<br>":"круг<br>",
    "square":"квадрат",
    "Background image:":"Фоновое изображение:",
    "Show noise":"Шум на изображении",
    "Show text above the button":"Текст над кнопкой",
    "Show arrow":"Стрелочка к кнопке",
    "Show text under the form title":"Текст под заголовком формы",
    "Show third title":"Доп. подзаголовок",
    "Show image around":"Рамка у изображения",
    "Show shadow from media":"Тень у изображения",
    "Show list box":"Список под описанием",
    "Form align:":"Расположение формы:",
    "left<br>":"слева<br>",
    "center<br>":"по центру<br>",
    "right":"справа",
    "Background texture:":"Текстура фона",
    "Show image name":"Заголовок изображения",
    "Show image signature":"Описание изображения",
    "Show image descroption":"Подзаголовок изображения",
    "Show big image (enable fancybox)":"Увеличение при клике",
    "Show second text title":"Дополнительный заголовок",
    "Show border":"Рамка",
    "Video size:":"Размер видео:",
    "small<br>":"маленький<br>",
    "medium<br>":"средний<br>",
    "Show name company":"Название компании",
    "Show branch company":"Отрасль",
    "Is displayed when you hover over the photo":"Выводится при наведении на фотографию",
    "Show order form":"Показавать форму",
    "Go to the link":"Переходить по ссылке",
    "Form":"Форма",
    "Link":"Ссылка",
    "Button behavior after click:":"Поведение кнопки заказа (после клика):",
    "Text":"Текст",
    "Text area":"Текстовое поле",
    "Checkbox":"Флажок",
    "Select":"Выпадающий список",
    "Radio":"Переключатель",
    "File":"Файл",
    "Order button":"Кнопка заказа",
    "Sunday":"Воскресенье",
    "Monday":"Понедельник",
    "Tuesday":"Вторник",
    "Wednesday":"Среда",
    "Thursday":"Четверг",
    "Friday":"Пятница",
    "Saturday":"Суббота",
}