exports = {
    "Add Section":"Добавить секцию",
    "Select component type":"Выбрать тип",
    "Document alert":"",
    "Preview":"Просмотр",
    "Editor":"Констуктор",
    "Publish":"Публиковать",
    "Your page was successfully published and now is available to your customers":"Ваша страница успешно опубликована и сейчас доступна для пользователей",
    "Publish success":"Публикация успешна",
    "Sure to remove component?":"Уверены. что хотите удалить компонент?",
    "Settings":"Настройки",
    "Add Item":"Добавить",
    "Logotype":"Логотип",
    "Image logo":"Изображение логотипа",
    "Text name logo":"Название логотипа",
    "Upload file":"Загрузить файл",
    "Company name:":"Название компании:",
    "Font settings:":"Настройки шрифта:",
    "Size:":"Размер:",
    "Icons":"Иконки",
    "Text":"Текст",
    "Field label":"Заголовок поля",
    "Field description":"Описание поля",
    "Is required?":"Обязательное для ввода?",
    "Text area":"Текстовое поле",
    "Checkbox":"Галочка",
    "Select":"Выпадающее меню",
    "Вариант 1\\nВариант 2\\nВариант 3":"",
    "Options":"Опции",
    "Radio":"Переключатель",
    "File":"Файл",
    "Form":"Форма",
    "Add Field":"Добавить поле",
    "Button text:":"Текст кнопки:",
    "Button color:":"Цвет кнопки:",
    "Show success window":"Окно благодарности",
    "Image":"Изображение",
    "Select image file":"Выбирите изображение",
    "Upload image file":"Загрузить изображение",
    "Order button":"Кнопка заказа",
    "Button behavior after click:":"Поведение кнопки после клика:",
    "Show order form":"Показать форму заказа",
    "Go to the link":"Перейти по ссылке",
    "Link":"Ссылка",
    "Show form":"Показать форму",
    "Media files":"Медиафайлы",
    "Video":"Видео",
    "Video url (youtube or vimeo):":"Видео ссылка:",
    "example: www.youtube.com\/embed\/xbK8rl9wH4Q":"пример: www.youtube.com\/embed\/xbK8rl9wH4Q",
    "Exact date":"Дата окончания",
    "Every month":"Ежемесячно",
    "Every week":"Еженедельно",
    "Every day":"Ежедневно",
    "Date:":"Дата:",
    "Day:":"День:",
    "Day of week:":"День недели:",
    "Time:":"Время:",
    "Image title:":"Заголовок изображения:",
    "Image description:":"Подзаголовок изображения:",
    "Upload image":"Загрузить изображение",
    "Show description and order button":"Описание и кнопка заказа",
    "Show order button":"Кнопка заказа",
    "Background color:":"Цвет фона:",
    "Background image:":"Фоновое изображение:",
    "Add noise":"Добавить шум",
    "Show text above the button":"Текст над кнопкой",
    "Add arrow":"Добавить стрелочку",
    "Show text under the form title":"Подзаголовок формы",
    "Show second title":"Подзаголовок",
    "Show third title":"Доп. подзаголовок",
    "Show text under the form":"Текст под формой",
    "Show border from media":"Края у медиа",
    "Show list box":"Список",
    "Form align:":"Положение формы:",
    "Move left<br>":"слева<br>",
    "Move center<br>":"по центру<br>",
    "Move right":"справа",
    "Background texture:":"Текстура фона:",
    "Show first title":"Заголовок",
    "Show border from icon":"Края у иконки",
    "Show name benefit":"Название преимущества",
    "Show description benefit":"Описание преимущества",
    "Show border from image":"Края у изображения",
    "Show image":"Показывать изображение",
    "Show name":"Назваие",
    "Show description":"Описание",
    "Show price":"Цена",
    "Show text above order button":"Показывать ",
    "Show shadow":"Добавить тень",
    "Image size:":"Размер изображения:",
    "middle<br>":"средний<br>",
    "large":"большой",
    "Image format:":"Форма изображения:",
    "circle<br>":"круг<br>",
    "square":"квадрат",
    "Show image name":"Название изображения",
    "Show image signature":"Подпись изображения",
    "Show image descroption":"Описание изображение",
    "Show big image (enable fancybox)":"Увеличивать при клике(вкл. fancybox)",
    "Grayscale logo":"Обесцветить лого",
    "Show name company":"Название компании",
    "Show branch company":"Направление компании",
    "Show name step":"Название шага",
    "Show description step":"Описание шага",
    "Add placemark":"Добавить метку",
    "center":"центр",
    "Show text":"Показать текст",
    "Name":"Название",
    "Address":"Адрес",
    "Color":"Цвет",
    "Show policy":"Политика конфиденциальности",
    "Show copyright":"Права",
    "Show second text title":"Текст под заголовом",
    "Show border":"Добавить обводку",
    "Video size:":"Размер видео:",
    "small<br>":"маленький<br>",
    "medium<br>":"средний<br>",
    "Show list":"Добавить список",
    "Show name cell":"Название",
    "Show description cell":"Описание",
    "Icons color:":"Цвет иконок:",
    "black":"черный",
    "grey":"серый",
    "white":"белый",
    "Digits color:":"Цвет цифр:",
    "Background:":"Фон:",
    "Countdown color:":"Цвет таймера:",
    "Second title color:":"Цвет подзаголовка:",
    "Show image border":"Рамка у картинки",
    "Media file":"Медиа файл",
    "Select file":"Выбрать файл",
    "Countdown settings":"",
    "Exact date<br>":"Дата окончания",
    "Every month<br>":"Ежемесячно",
    "Every week<br>":"Еженедельно",
    "Every day<br>":"Ежедневно",
    "Monday":"Понедельник",
    "Tuesday":"Вторник",
    "Wednesday":"Среда",
    "Thursday":"Четверг",
    "Friday":"Пятница",
    "Saturday":"Суббота",
    "Sunday":"Воскресенье",
    "Option 1\\nOption 2\\nOption 3":"Вариант 1\\nВариант 2\\nВариант 3",
    "Show icon around":"Линия вокруг иконки",
    "Show image around":"Рамка у изображения",
    "Show image shadow":"Добавить тень",
    "Show shadow under image":"Тень под изображением",
    "Image shape:":"Форма изображения:",
    "Show noise":"Добавить шум к изображению",
    "Show arrow":"Стрелочка к кнопке",
    "left<br>":"слева<br>",
    "center<br>":"по центру<br>",
    "right":"справа",
    "Show image title":"Название изображения",
    "Show block description under image":"Текстовый блок под изображением",
    "Show image description":"Описание изображения",
    "Numbers color:":"Цвет цифр:"
}