exports = {
    "Add Section":"",
    "Show first title":"",
    "Show second title":"",
    "Grayscale logo":"",
    "Background color:":"",
    "Show text under the form":"",
    "Countdown color:":"",
    "Second title color:":"",
    "Background:":"",
    "Show list":"",
    "Show name cell":"",
    "Show description cell":"",
    "Show border from image":"",
    "Show policy":"",
    "Show copyright":"",
    "Add placemark":"",
    "center":"",
    "Show text":"",
    "Name":"",
    "Address":"",
    "Color":"",
    "Upload file":"",
    "Video":"",
    "Video url (youtube or vimeo):":"",
    "example: www.youtube.com\/embed\/xbK8rl9wH4Q":"",
    "Image":"",
    "Select image file":"",
    "Upload image file":"",
    "Order form":"",
    "Button text:":"",
    "Button color:":"",
    "Form:":"",
    "Show form":"",
    "Show success window":"",
    "Add Item":"",
    "Media files":"",
    "Upload image":"",
    "Image title:":"",
    "Image description:":"",
    "Exact date":"",
    "Every month":"",
    "Every week":"",
    "Every day":"",
    "Date:":"",
    "Day:":"",
    "Day of week:":"",
    "Time:":"",
    "Map":"",
    "Logotype":"",
    "Image logo":"",
    "Text name logo":"",
    "Company name:":"",
    "Font settings:":"",
    "Size:":"",
    "Field label":"",
    "Field description":"",
    "Is required?":"",
    "Option 1\\nOption 2\\nOption 3":"",
    "Options":"",
    "Form":"",
    "Add Field":"",
    "Sure to remove component?":"",
    "Settings":"",
    "Icons":"",
    "Show description and order button":"",
    "Show order button":"",
    "Show border from icon":"",
    "Show name benefit":"",
    "Show description benefit":"",
    "Show name step":"",
    "Show description step":"",
    "Show image":"",
    "Icons color:":"",
    "black":"",
    "grey":"",
    "white":"",
    "Digits color:":"",
    "Show name":"",
    "Show description":"",
    "Show price":"",
    "Show text above order button":"",
    "Show shadow":"",
    "Image size:":"",
    "middle<br>":"",
    "large":"",
    "Image format:":"",
    "circle<br>":"",
    "square":"",
    "Background image:":"",
    "Add noise":"",
    "Show text above the button":"",
    "Add arrow":"",
    "Show text under the form title":"",
    "Show third title":"",
    "Show border from media":"",
    "Show shadow from media":"",
    "Show list box":"",
    "Form align:":"",
    "Move left<br>":"",
    "Move center<br>":"",
    "Move right":"",
    "Background texture:":"",
    "Show image name hover":"",
    "Show image descroption hover":"",
    "Show image signature":"",
    "Show big image (enable fancybox)":"",
    "Show second text title":"",
    "Show border":"",
    "Video size:":"",
    "small<br>":"",
    "medium<br>":"",
    "Show name company":"",
    "Show branch company":""
}