@import "bake.min.js";

@ color1 = '#123';
@ color2 = '#f90';
@ sheetWidth = 760;

.background_striped(size,width,color) {
    @{
        var canvas = (new Canvas(size,size))
        .draw2D(function(ctx){
            ctx.beginPath();
            ctx.lineWidth = width;
            ctx.strokeStyle = color.toString();
            ctx.moveTo(-size,-size); ctx.lineTo(size*2,size*2);
            ctx.moveTo(-size-size,-size); ctx.lineTo(size,size*2);
            ctx.moveTo(-size+size,-size); ctx.lineTo(size*3,size*2);
            ctx.stroke();
        });
    }
    background-image: url(@{canvas.toDataURL()});
}

.logo(url,w,h) {
    display: block;
    background: url(@url) no-repeat 50% 50%;
    width: @{w}px;
    height: @{h}px;
    text-indent: -999em;
}

.reset();
.typography();
.form();

form {
    padding: 0;

    button[type="submit"] {
        .button({color:color(1,11)});
        font-size: 1.4em;
        line-height: 1.2em;
    }
    input[type="text"],select,textarea {
        max-width: 600px;
    }
    .mceEditor .mceLayout {
        max-width: 1200px;
        margin-bottom: 0.8em;
    }
    
    .browse_wrap {
        max-width: 600px;
        margin: 0 0 0.8em 0;
        
        background: none !important;
        tr,td {
            background: none !important;
            border: none;
            padding: 0;
        }
        input {
            margin: 0;
        }
        button {
            .button({color:color(1,11)});
            margin-left: 0.5em;
        }
    }
}

.table({bordered:true,striped:true});

.message, .alert {
    .alerts();
}

html {
    height: 100%;
}

body {
    min-height: 100%;
    position: relative;
}

body {
    .background_striped(4,2,"#ddd");
}

#page {
    padding: 0px 0px 50px 170px;
    box-sizing: border-box;
    min-height: 100%;
}

#menu {
    z-index: 1;
    position: fixed;
    background: white;
    left: 0; width: 170px;
    top: 0px; bottom: 0px;
    .box_shadow("2px 0px 5px rgba(0,0,0,0.2)");
    
    
    ul {
        margin: 0;
    
        li {
            a {
                display: block;
                font-size: 1.2em;
                padding: 0.7em 1em;
                border-right: none;
                border-left: none;
                text-decoration: none;
            }
            
            #logo {
                .logo("/assets/images/lpcandy.png",135,103);
                margin: 10px auto;
                border: none;
                padding: 0;
                .box_shadow('none');
            }
        }
        
        a:hover, li.current-menu-item a  {
            .box_shadow("0px 0px 5px rgba(0,0,0,0.3) inset");
        }
    }
}

#logged_info {
    background: none repeat scroll 0 0 #333333;
    border-bottom: 2px solid #777777;
    border-left: 2px solid #777777;
    border-radius: 0 0 0 20px;
    margin: 0 !important;
    padding: 5px 10px 5px 15px;
    position: absolute;
    right: 0;
    top: 0;
    color: #aaa;
    white-space: nowrap;
    z-index: 50000;
}

#logged_info a {
    color: #fff;
    text-decoration: none;
}

#logged_info a.home {
    width: 20px;
    height: 20px;
	background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABLUlEQVR4nM2UvUoDQRRGzwZFI1aCD2BnIVoKBgKCkE58ABEshfgoNmJhK76DIIKFBLGxVTSFoJWd+BOVCMcio5ks65poBD9YZu+duWdmvpndRKWfKvSVBgx0MWYUmAOOgceQKwMjQAM46hit5j2Tat2WztWJkI/VUZMHq6h3oeg0tLfq7E+A6+qb2lSrAVINcSMPmD6UQWAb2AQegCVgBjgBpoFF4DnX8Yg+ph6GWS/UslpLraamltSzKDeeteXY/AN1Qb0xW9fqvLoX4it1KgaWbJu/pa5k+JRWQ11WN0J8HyahADyF3a+Fe7YDFL+5m0VgF2gCq4Af3ia2Pr0h4DV09KoEGAZeYuDnGWUU7EfvlS+A7aALYNJDf/9/Dn8OrPdYf5lOpD38tf6/h+9paMshEIIyawAAAABJRU5ErkJggg==');
    display: inline-block;
    vertical-align: bottom;
    margin-left: -5px;
}

#content {
    > h3 {
        background: #333;
        color: white;
        border-top: 5px solid @color(1,11);
        
        margin: 0px;
        padding: 10px 20px;
    }
    
    > form > table, > section > form > fieldset {
        background: white;
        box-shadow: 0px 0px 3px rgba(0,0,0,0.2);
    }
    
    > form  {
        margin: 10px 10px 0;
    }
    
    > section > form > fieldset {
        padding: 10px;
        margin: 10px 10px 0;
    }
}

#footer {
    position: absolute;
    bottom: 0px;
    left: 170px; right: 0px;

    border-top: 5px solid @color(1,11);
    background: #333;
    
    text-align: center;
    box-sizing: border-box;
    height: 55px;
    line-height: 50px;
    
    overflow: hidden;
    
    #beejee_info {
        color: #aaa;
        display: inline-block;
        text-decoration: none;
        
        > span {
            .logo('/assets/images/logo-beejee.jpg',30,30);
            vertical-align: middle;
            display: inline-block;
            margin-right: 5px;
        }

        > p {
            display: inline-block;
            vertical-align: middle;
            text-align: left;
            font-size: 14px;
            line-height: 1.2em;
            font-family: Arial;

            span {
                color: #FF0;
                
            }
        }
    }
}

.pagination {
    margin-bottom:0.5em;
    clear: both;
    overflow: hidden;

    ul {
        display:block;
        margin: 0;

        li {
            display:block;
            float:left;
            width: auto;
            min-width:25px;
            margin:2px;
            text-align:center;
            background:#fff;
            border:1px solid #aaa; 
            line-height:1.5em; 
            font-size:12px;
            border-radius:5px;
            
            a {
                color:#333;
                text-decoration: none;
            }
            
            &.current {
                background: @color(1,10);
            }
            
        }
    }
}

table.list tbody {
    tr.filter {
        th {
            background: @color(1,14);
        }
        button {
            .button({color:color(1,8)});
        }
        input,select {
            margin: 0;
        }
    }
}

.sort-field {
    text-decoration: none;
    white-space: nowrap;
    
    &.ASC:after {
        content: " ▲";
    }

    &.DESC:after {
        content: " ▼";
    }
}
    


table.list {
    border-radius: 0;
    td, th {
        vertical-align: middle;
    }
    margin-bottom: 1em;
}

.page-title {
    line-height: 20px;
    margin-bottom: 10px;
    border-bottom: 2px solid #eee;
    
    .page_actions {
        font-size: 12px;
        line-height: 14px;
        margin-left: 1em;
        a {
            .button({color:color(2,8)});
            text-decoration: none;
        }
    }
}

td.preview {
    text-align: right;
    width: 1px;
    padding: 20px;
}

td.title {
    padding: 20px;
}

td.preview img {
    border: 1px solid #ddd;
}

td.title h3 {
    margin-bottom: 0.3em;
}

td.title h3 a {
    font-size: 12px;
}

.child td.title h3 {
    font-size: 14px;
}

.actions {
    margin-top: 0.5em;

    a {
        .button({color:color(1,11)});
        &.delete {
            .button({color:'#a00'});
        }
        
        &, &:hover {
            text-decoration: none;
        }
        
        &.design {
            font-size: 1.4em;
            line-height: 1.2em;
            margin: 0.4em auto;
        }
        
        .child & {
            font-size: 1.0em;
        }
    }
}

p.actions {
    a {
        .button({color:'green'});
    }
}

.template-select {
    label {
        width: 240px;
        display: inline-block;
        vertical-align: top;
        margin: 0 10px 20px 0;
        position: relative;
        padding-top: 160px;
        text-align: center;
        
        img {
            position: absolute;
            top: 0;
            left: 50%;
            width: 200px;
            margin-left: -100px;
        }
    }
}

#home-landing {
    position: fixed;
    width: calc(100vw - 170px);
    height: 100vh;
}