window._t.load({
    "HTML": "HTML",
    "Background color": "Цвет фона",
    "Confirm": "Подтверждение",
    "Alert": "",
    "new": "новая",
    "in progress": "в работе",
    "done": "готова",
    "canceled": "отменена",
    "#": "№",
    "page": "страница",
    "status": "статус",
    "date": "дата",
    "ip addr": "ip адрес",
    "data": "данные",
    "delete": "удалить",
    "Tracks": "Заявки",
    "Client track": "Заявка клиента",
    "Client tracks": "Заявки клиентов",
    "Bold": "Жирный",
    "Italic": "Наклонный",
    "Deleted": "Зачеркнутый",
    "Clear format": "Без форматирования",
    "Font size": "Размер шрифта",
    "Text color": "Цвет текста",
    "filter": "фильтр",
    "Logout": "Выйти",
    "Login": "Войти",
    "Pages": "Страницы",
    "Profile": "Профиль",
    "LPCandy is developed by": "LPCandy разработана ",
    "is looking for mind-blowing project": "в поиске крутого проекта",
    "You can get an account on this site, if you have an account in the popular social networks or services. Select the authentication method below. If you already went this way on this site, you already have an account.": 
    "Вы можете получить учетную запись на этом сайте, если у вас есть учетная запись в популярных социальных сетях или сервисах. Выберите способ авторизации ниже. Если вы уже заходили подобным образом на этом сайте, то у вас уже есть учетная запись.",
    "Create page": "Создать страницу",
    "Title": "Заголовок",
    "Domain": "Домен",
    "Start from scratch": "Начать с нуля",
    "Edit page": "Редактировать страницу",
    "Path relative to parent": "Относительный путь",
    "Meta tag \"robots\" content": "Метатэг robots",
    "Meta tag \"keywords\" content": "Метатэг keywords",
    "Meta tag \"description\" content": "Метатэг description",
    "Save page": "Сохранить страницу",
    "(page preview)": "(просмотр)",
    "No domain assigned": "Нет домена",
    "+ add child page": "+ добавить подстраницу",
    "Launch Designer": "Запустить редактор",
    "Edit": "Изменить",
    "Delete": "Удалить",
    "Create New Landing Page": "Создать новую страницу",
    "No pages yet": "Страниц пока нет",
    "User profile": "Профиль пользователя",
    "Email for notifications": "Почта для уведомлений",
    "Save": "Сохранить",
    "days": "дни",
    "hours": "часы",
    "minutes": "минуты",
    "seconds": "секунды",
    "field is required": "обязательное поле",
    "bold": "жирный",
    "italic": "наклонный",
    "Yes": "Да",
    "Cancel": "Отмена",
    "Preview": "Просмотр",
    "Publish": "Публиковать",
    "Editor": "Констуктор",
    "Add Section": "Добавить секцию",
    "Select component type": "Выбрать тип",
    "Your page was successfully published and now is available to your customers": "Ваша страница успешно опубликована и сейчас доступна для пользователей",
    "Publish success": "Публикация успешна",
    "Publish failed": "Ошибка публикации",
    "Show icon": "Иконка",
    "Show form as popup": "Всплывающая форма",
    "Map is draggable": "Можно перетаскивать карту",
    "Document alert": "",
    "Sure to remove component?": "Уверены, что хотите удалить компонент?",
    "Settings": "Настройки",
    "Add Item": "Добавить",
    "Logotype": "Логотип",
    "Image logo": "Изображение",
    "Text name logo": "Текст",
    "Upload file": "Загрузить файл",
    "Company name:": "Название компании:",
    "Font settings:": "Настройки шрифта:",
    "Size:": "Размер:",
    "Icons": "Иконки",
    "Text": "Текст",
    "Field label": "Заголовок поля",
    "Field description": "Описание поля",
    "Field placeholder": "Заполнитель поля",
    "Is required?": "Обязательное для ввода?",
    "Text area": "Текстовое поле",
    "Checkbox": "Галочка",
    "Select": "Выпадающее меню",
    "Вариант 1\\nВариант 2\\nВариант 3": "",
    "Options": "Опции",
    "Radio": "Переключатель",
    "File": "Файл",
    "Form": "Форма",
    "Add Field": "Добавить поле",
    "Button text:": "Текст кнопки:",
    "Button color:": "Цвет кнопки:",
    "Show success window": "Окно благодарности",
    "Image": "Изображение",
    "Select image file": "Выбирите изображение",
    "Upload image file": "Загрузить изображение",
    "Order button": "Кнопка заказа",
    "Button behavior after click:": "Поведение кнопки после клика:",
    "Show order form": "Показать форму заказа",
    "Go to the link": "Перейти по ссылке",
    "Link": "Ссылка",
    "Show form": "Показать форму",
    "Media files": "Медиафайлы",
    "Video": "Видео",
    "Video url (youtube or vimeo):": "Видео ссылка:",
    "Exact date": "Дата окончания",
    "Every month": "Ежемесячно",
    "Every week": "Еженедельно",
    "Every day": "Ежедневно",
    "Date:": "Дата:",
    "Day:": "День:",
    "Day of week:": "День недели:",
    "Time:": "Время:",
    "Image title:": "Заголовок изображения:",
    "Image description:": "Подзаголовок изображения:",
    "Upload image": "Загрузить изображение",
    "Show description and order button": "Описание и кнопка заказа",
    "Show order button": "Кнопка заказа",
    "Background color:": "Цвет фона:",
    "Background image:": "Фоновое изображение:",
    "Add noise": "Добавить шум",
    "Show text above the button": "Текст над кнопкой",
    "Add arrow": "Добавить стрелочку",
    "Show text under the form title": "Подзаголовок формы",
    "Show second title": "Подзаголовок",
    "Show third title": "Доп. подзаголовок",
    "Show text under the form": "Текст под формой",
    "Show border from media": "Края у медиа",
    "Show list box": "Список",
    "Form align:": "Положение формы:",
    "Move left<br>": "слева<br>",
    "Move center<br>": "по центру<br>",
    "Move right": "справа",
    "Background texture:": "Текстура фона:",
    "Show first title": "Заголовок",
    "Show icon border": "Края у иконки",
    "Show benefit name": "Название преимущества",
    "Show benefit desc": "Описание преимущества",
    "Show image border": "Рамка у картинки",
    "Show image": "Показывать изображение",
    "Show name": "Назваие",
    "Show description": "Описание",
    "Show price": "Цена",
    "Show text above order button": "Показывать ",
    "Show shadow": "Добавить тень",
    "Image size:": "Размер изображения:",
    "middle": "средний",
    "large": "большой",
    "Image format:": "Форма изображения:",
    "circle": "круг",
    "square": "квадрат",
    "Show image name": "Название изображения",
    "Show image signature": "Подпись изображения",
    "Show image descroption": "Описание изображение",
    "Show big image": "Увеличивать при клике",
    "Grayscale logo": "Обесцветить лого",
    "Show name company": "Название компании",
    "Show branch company": "Направление компании",
    "Show name step": "Название шага",
    "Show description step": "Описание шага",
    "Add placemark": "Добавить метку",
    "center": "по центру",
    "Show text": "Показать текст",
    "Name": "Название",
    "Address": "Адрес",
    "Color": "Цвет",
    "Show policy": "Политика конфиденциальности",
    "Show copyright": "Права",
    "Show second text title": "Текст под заголовом",
    "Show border": "Добавить рамку",
    "Video size:": "Размер видео:",
    "small": "маленький",
    "medium": "средний",
    "Show list": "Добавить список",
    "Show name cell": "Название",
    "Show description cell": "",
    "Icons color:": "Цвет иконок:",
    "black": "черный",
    "grey": "серый",
    "white": "белый",
    "Digits color:": "Цвет цифр:",
    "Background:": "Фон:",
    "Countdown color:": "Цвет таймера:",
    "Second title color:": "Цвет подзаголовка:",
    "Show second name": "Подзаголовок",
    "Media file": "Медиа файл",
    "Select file": "Выбрать файл",
    "Countdown settings": "Настройки таймера",
    "Exact date<br>": "Дата окончания<br>",
    "Every month<br>": "Ежемесячно<br>",
    "Every week<br>": "Еженедельно<br>",
    "Every day<br>": "Ежедневно<br>",
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница",
    "Saturday": "Суббота",
    "Sunday": "Воскресенье",
    "Option 1\\nOption 2\\nOption 3": "Вариант 1\\nВариант 2\\nВариант 3",
    "Remove confirmation": "Подтвердите удаление",
    "Show icon around": "Линия вокруг иконки",
    "Show image around": "Рамка у изображения",
    "Show image shadow": "Добавить тень",
    "Show shadow under image": "Тень под изображением",
    "Image shape:": "Форма изображения:",
    "Show noise": "Добавить шум к изображению",
    "Show arrow": "Стрелочка к кнопке",
    "left": "слева",
    "right": "справа",
    "Show image title": "Название изображения",
    "Show block with text": "Блок с текстом",
    "Show image description": "Описание изображения",
    "Numbers color:": "Цвет цифр:",
    "Template": "Шаблон",
    "Dark background": "Темный фон",
    "Two column layout": "Шаблон в две колонки",
    "Information policy": "Политика конфиденциальности",
    "Benefits": "Преимущества",
    "Main advantages": "Ваши главные преимущества",
    "Cases": "Кейсы",
    "The results of our customers": "Результаты наших клиентов",
    "Cover": "Обложка",
    "Custom html+css": "Ваш собственный html+css",
    "FAQ": "ЧаВо",
    "Questions and answers": "Частые вопросы",
    "Feedback": "Отзывы",
    "Customer reviews": "Отзывы наших клиентов",
    "Footer": "Подвал",
    "The final block": "Завершающий блок",
    "Gallery": "Галерея",
    "Photos and images": "Фотографии работ",
    "Header": "Шапка",
    "Logo and contacts": "Логотип и контакты компании",
    "Logos": "Логотипы",
    "Logos of the partners": "Логотипы партнёров",
    "Contacts": "Контакты",
    "Company contacts": "Карта и адреса",
    "Numbers": "Цифры",
    "Indicators company": "Показатели компании",
    "Order": "Заявка",
    "Block with a picture and form": "Блок с картинкой и формой",
    "Reasons": "Почему мы",
    "Otherness": "Отличие от конкурентов",
    "Services": "Услуги",
    "List of services": "Перечень услуг",
    "Stages": "Порядок работы",
    "Work order": "Основные этапы работы",
    "Sticky menu": "Липкое меню",
    "Navigation menu": "Меню навигации",
    "Text blocks": "Текстовые блоки",
    "Countdown": "Таймер",
    "Countdown for the stock": "Счетчик для акций",
    "Add video": "Вставка видео"
});