exports = {
    ...require("AddBlockDialog/AddBlockDialog"),
    ...require("Block/Block"),
    ...require("Color/Color"),
    ...require("Combo/Combo"),
    ...require("Cover/Cover"),
    ...require("Dialog/Dialog"),
    ...require("Editable/Editable"),
    ...require("Icon/Icon"),
    ...require("Image/Image"),
    ...require("Portal/Portal"),
    ...require("Repeater/Repeater"),
    ...require("Switch/Switch"),
    ...require("Text/Text"),
    ...require("UploadButton/UploadButton"),
}